language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install .
  - pip install nose-cov

# command to run tests
script:
  - nosetests --with-cov --cov-report xml
  - bash <(curl -S https://codecov.io/bash)
