language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# command to install dependencies
install:
  - pip install .
  - pip install nose-cov

# command to run tests
script:
  - nosetests --with-cov --cov-report xml
  - bash <(curl -S https://codecov.io/bash)
